spring:
  config:
    activate:
      on-profile: "qa"
build:
  version: "0.2"

loans:
  message: "Loans microservice is active in UAT environment"
  contactDetails:
    name: "Muthyalu Bhavesh"
    email: "bhavesh16281@gmail.com"
    phone: "+91 8309828565"