spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "0.3"

loans:
  message: "Loans microservice is active in Production environment"
  contactDetails:
    name: "Muthyalu Bhavesh"
    email: "bhavesh16281@gmail.com"
    phone: "+91 8309828565"